language: go

go:
  - tip
  - 1.5
  - 1.4
  - 1.3

os:
  - linux
  - osx

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/gopistolet/gospf
  - go get github.com/sloonz/go-maildir
  - go get code.google.com/p/go.net/websocket
